// Interface automatically generated by schemas-to-ts

import { Media } from "./Media"
export enum Tag {
  Journal = "journal",
  Stationary = "stationary",
  Accessories = "accessories",
  Homeware = "homeware",
  Gifts = "gifts",
}

export interface Product {
  id: number
  attributes: {
    createdAt: Date
    updatedAt: Date
    publishedAt?: Date
    description: string
    active: boolean
    title: string
    gallery: { data: Media[] }
    slug: string
    priceId: string
    subtitle: string
    tag: Tag
  }
}
